# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: fcadf6aca2690fda26c407b1a5ed9aa9e165dcf8b786ff710e072e8f76717d44b329d28c0152b87baa12c4a08bb557c99661d4895c5894715a20824e021d58d5

test:
  secret_key_base: af4e68055cf00693f68448f7458c964151b3920bc5cb0bf09c116db9badc3602608fe187a31ffa147469a9d7e2820031abdda8e45127e4fdd72ecb0e40388e8e

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
